import { useDeleteCourseCommentLike } from "../courses";

export const APIRoutes = {
  loginAPI: "/sign/login",
  SignApi: "/Sign/SendVerifyMessage",
  getCourseTop: "/Home/GetCoursesTop",
  getProfile: "/SharePanel/GetProfileInfo",
  AddProfileImage: "/SharePanel/AddProfileImage",
  ChangePassword: "/SharePanel/ChangePassword",
  MyCourses: "/SharePanel/GetMyCourses",
  getAllCourses: "/Home/GetCoursesWithPagination",
  SignRegester: "/Sign/Register",
  RessetPassword: "/Sign/ForgetPassword",
  RessetPass3: "/Sign/Reset",
  VerifyMessage: "/Sign/VerifyMessage",
  Allteacher: "/Home/GetTeachers",
  TopNews: "/News",
  // AllNews:"/News/GetListNewsCategory",
  LandingReport: "/Home/LandingReport",
  CourseId: `/Home/GetCourseDetails`,
  Coursecomment: "/Course/GetCourseCommnets",
  CourseReplyCommnets: "Course/GetCourseReplyCommnets",
  NewsId: "/News/",
  GetCoursesWithPagination: "/Home/GetCoursesWithPagination",
  CourseLevel: "/CourseLevel/GetAllCourseLevel",
  CourseType: "/CourseType/GetCourseTypes",
  Technologies: "/Home/GetTechnologies",
  EditProfile: "/SharePanel/UpdateProfileInfo",
  GetProfileInfo: "/SharePanel/GetProfileInfo",
  NewsLike: "/News/NewsLike",
  RepliesComments: "/News/GetRepliesComments?Id=",
  CommentLike: "/News/CommentLike",
  NewsDissLike: "/News/NewsDissLike",
  AddFavoriteNews: "/News/AddFavoriteNews?NewsId=",
  DeleteFavoriteNews: "/News/DeleteFavoriteNews",
  AddCourseLike: "/Course/AddCourseLike?CourseId=",
  CourseRating: "/Course/SetCourseRating?CourseId=",
  NewsRate: "/News/NewsRate",
  AddCourseDissLike: "/Course/AddCourseDissLike?CourseId=",
  AddCourseFavorite: "/Course/AddCourseFavorite",
  ReserveAdd: "/CourseReserve/ReserveAdd?courseId=",
  DeleteCourseReserve: "/CourseReserve",
  AddReplyCourseComment: "/Course/AddReplyCourseComment",
  AddCommentCourse: "/Course/AddCommentCourse",
  MyFavoriteCourses: "/SharePanel/GetMyFavoriteCourses",
  MyFavoriteNews: "SharePanel/GetMyFavoriteNews",
  MyCoursesReserve: "/SharePanel/GetMyCoursesReserve",
  AddProfileImage: "/SharePanel/AddProfileImage",
  AddCourseCommentLike: "/Course/AddCourseCommentLike?CourseCommandId=",
  AddCourseCommentDissLike: "Course/AddCourseCommentDissLike?CourseCommandId=",
  DeleteCourseComment: "/Course/DeleteCourseComment",
  DeleteCourseCommentLike: "/Course/DeleteCourseCommentLike",
  DeleteProfileImage:"/SharePanel/DeleteProfileImage",
};
